# Generated by Django 4.1.3 on 2022-11-05 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgregadoAlmuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
                ('cantidad', models.CharField(max_length=50)),
                ('time', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseBowl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CorteKai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('envoltorio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraBowl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(default=0, null=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraKai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('categoria', models.CharField(max_length=32)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProteinaAlmuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinaBowl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(null=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinaDesayuno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinaHandroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuesoDesayuno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalsaBowl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Selladitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0, null=True)),
                ('state', models.BooleanField(default=True)),
                ('typ', models.CharField(default='sell', max_length=50)),
                ('time', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VegetalesDesayuno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VegetalesHandroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0, null=True)),
                ('typ', models.CharField(default='kai', max_length=50)),
                ('time', models.FloatField(default=0, null=True)),
                ('corte1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.corte1+', to='core.cortekai')),
                ('corte2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.corte2+', to='core.cortekai')),
                ('corte3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.corte3+', to='core.cortekai')),
                ('corte4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.corte4+', to='core.cortekai')),
                ('corte5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.corte5+', to='core.cortekai')),
                ('corte6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.corte6+', to='core.cortekai')),
                ('corte7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.corte7+', to='core.cortekai')),
                ('extra1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.extra1+', to='core.extrakai')),
                ('extra2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.extra2+', to='core.extrakai')),
                ('extra3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.extra3+', to='core.extrakai')),
                ('extra4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.extra4+', to='core.extrakai')),
                ('extra5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.extra5+', to='core.extrakai')),
            ],
        ),
        migrations.CreateModel(
            name='HandrollReady',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('typ', models.CharField(default='hc', max_length=50)),
                ('time', models.FloatField(default=0, null=True)),
                ('proteina1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HandrollReady.proteina1+', to='core.proteinahandroll')),
                ('proteina2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HandrollReady.proteina2+', to='core.proteinahandroll')),
                ('proteina3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HandrollReady.proteina3+', to='core.proteinahandroll')),
                ('vegetal1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HandrollReady.vegetal1+', to='core.vegetaleshandroll')),
                ('vegetal2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HandrollReady.vegatal2+', to='core.vegetaleshandroll')),
                ('vegetal3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HandrollReady.vegetal3+', to='core.vegetaleshandroll')),
            ],
        ),
        migrations.CreateModel(
            name='Handroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('typ', models.CharField(default='h', max_length=50)),
                ('time', models.FloatField(default=0, null=True)),
                ('proteina1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Handroll.proteina1+', to='core.proteinahandroll')),
                ('proteina2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Handroll.proteina2+', to='core.proteinahandroll')),
                ('proteina3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Handroll.proteina3+', to='core.proteinahandroll')),
                ('vegetal1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Handroll.vegetal1+', to='core.vegetaleshandroll')),
                ('vegetal2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Handroll.vegetal2+', to='core.vegetaleshandroll')),
                ('vegetal3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Handroll.vegetal3+', to='core.vegetaleshandroll')),
            ],
        ),
        migrations.CreateModel(
            name='Desayuno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('typ', models.CharField(default='des', max_length=50)),
                ('time', models.FloatField(default=0, null=True)),
                ('proteina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proteinadesayuno')),
                ('queso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quesodesayuno')),
                ('vegetal1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Desayuno.vegetal1+', to='core.vegetalesdesayuno')),
                ('vegetal2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Desayuno.vegetal2+', to='core.vegetalesdesayuno')),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(blank=True, null=True)),
                ('cooking', models.BooleanField(default=False)),
                ('time_to_kitchen', models.DateTimeField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('time_finished', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.FloatField(default=0, null=True)),
                ('coments', models.TextField(blank=True, null=True)),
                ('article', models.ManyToManyField(to='core.article')),
            ],
        ),
        migrations.CreateModel(
            name='Bowl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('typ', models.CharField(default='b', max_length=50)),
                ('time', models.FloatField(default=0, null=True)),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.basebowl')),
                ('extra1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.extra1+', to='core.extrabowl')),
                ('extra10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.extra10+', to='core.salsabowl')),
                ('extra2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.extra2+', to='core.salsabowl')),
                ('extra3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.extra3+', to='core.salsabowl')),
                ('extra4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.extra4+', to='core.salsabowl')),
                ('extra5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.extra5+', to='core.salsabowl')),
                ('extra6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.extra6+', to='core.salsabowl')),
                ('extra7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.extra7+', to='core.salsabowl')),
                ('extra8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.extra8+', to='core.salsabowl')),
                ('extra9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.extra9+', to='core.salsabowl')),
                ('proteina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proteinabowl')),
                ('salsa1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.salsa1+', to='core.salsabowl')),
                ('salsa2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kai.salsa2+', to='core.salsabowl')),
            ],
        ),
        migrations.CreateModel(
            name='Almuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(default='al', max_length=50)),
                ('time', models.FloatField(default=0, null=True)),
                ('price', models.PositiveIntegerField(default=0, null=True)),
                ('state', models.BooleanField(default=True)),
                ('agregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agregadoalmuerzo')),
                ('proteina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proteinaalmuerzo')),
            ],
        ),
    ]
